### ISSUE TITLE
Software Licence not showing on GravityForms drop-down.

### ISSUE THREAD

**Issue by adampickering** [Astoundify/donkey#25]
I purchased a plugin licence but when I visit the GravityForm it doesn't show the licence key, so cannot submit a ticket under that licence key.

![screen shot 2016-02-03 at 11 50 28 pm](https://cloud.githubusercontent.com/assets/746776/12806164/7d740a58-cad1-11e5-9177-734c640f482e.jpg)

![screen shot 2016-02-03 at 11 50 17 pm](https://cloud.githubusercontent.com/assets/746776/12806165/7d7885e2-cad1-11e5-9426-964c7040c1bd.jpg)

@spencerfinnell

**Comment by spencerfinnell** [comment]
The license needs to be active. 

http://docs.easydigitaldownloads.com/article/381-software-licensing-usage-instructions

NOTE: Newly created licenses are always set as inactive. They're not set as active until the customer activates them.
