### ISSUE TITLE
Plugin re-write ideas.

### ISSUE THREAD

**Issue by adampickering** [Astoundify/donkey#28]
What the re-write should do.

1. Allow customers to log into their Envato account via [edd_login], [edd_register] shortcodes.
2. Output the login option on the checkout page and create a WP user account.
3. Collect all user information that we currently collect in Donkey https://github.com/Astoundify/donkey/blob/master/src/inc/class-user.php#L20
4. Look via the API to see if the user has purchased one of our themes and add all licenses that the user has purchased to their WordPress user meta, showing only licenses that have a valid support subscription, on the first step of the GravityForms drop-down submission. This should check each time the user logs in.
5. If the user has already got an account using with the email address the system should merge the accounts? or ask them to reset their password?

@spencerfinnell is this what you were thinking? I would like us to start discussing this as @benjaminprojas will start work this monday. He needs to know how we want it to work and how to should be built.

Thanks!

**Comment by spencerfinnell** [comment]
In my opinion the EDD Envato Login should be developed as a separate plugin and the authentication should be removed from this plugin. It should just add a Envato login button to all EDD login forms and function like the other EDD Social Login plugin. 

The Add License functionality should also be removed from the plugin and replaced with the auto-addition of any of their Astoundify licenses based on the current user's linked Envato account. If they have a standard WordPress account they should be given an option to link their Envato account.

**Comment by greguly** [comment]
Hi folks, 

I commented at the task at Codeable but it was cancelled (and blocked) before I could thank you for the update, so here I do it :-)

Thanks for letting us know that you will handle this yourselves.

Cheers,
Gabriel
