### ISSUE TITLE
Add purchase date to Helpscout App Output

### ISSUE THREAD

**Issue by adampickering** [Astoundify/donkey#35]

**Comment by adampickering** [comment]
Formatted like:

![screen shot 2016-08-05 at 1 54 43 pm](https://cloud.githubusercontent.com/assets/746776/17445734/28f260fa-5b14-11e6-989b-7c4c27a4df88.jpg)

**Comment by turtlepod** [comment]
I have no idea about this subject. I'm not the one who write this plugin. Sorry.
