### ISSUE TITLE
Check for Expiration Time When Checking Licenses

### ISSUE THREAD

**Issue by spencerfinnell** [Astoundify/donkey#36]
https://github.com/Astoundify/donkey/blob/master/src/inc/class-user.php#L48

`get_token_expire_time()` will return 0 if it doesn't exist, which is always less than now! This will cause licenses to not refresh.

**Comment by turtlepod** [comment]
I fix this in latest EDD Envato Login.
So you don't need to check expiration time. the function `\edd_envato_login\envato_api\Functions::get_user_token()` will handle it.

example usage:
https://github.com/Astoundify/edd-envato-sync/blob/master/includes/functions.php#L45
